
language: node_js
node_js:
  - "10"
script: npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'vue-apps/services-azlist/production'
    on:
      branch: master
    local_dir: dist
    skip_cleanup: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'vue-apps/services-azlist/test'
    on:
      branch: test
    local_dir: dist
    skip_cleanup: true
